### ISSUE TITLE
Add crossdomain requests

### ISSUE THREAD

**Issue by benmccormick** [fif4evr/personally-api#11]
We need to allow the api to be accessed from other domains with AJAX requests.  Browsers disallow that by default, but you can permit it by setting the headers to allow it.  You can see instructions for doing that here:

http://flask.pocoo.org/snippets/56/

You'll want to pull that into a separate file and import it for defining your routes probably.

This is actually highish priority since the client can't access it without that.

**Comment by fif4evr** [comment]
test it out and let me know if what i did wasn't sufficient

**Comment by benmccormick** [comment]
What you did wasn't sufficient :smile:  but what you did the second time was fine.
